WARNING  kubetest:utils.py:139 got api exception while waiting: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1e7bb30e-f37e-4319-bf9c-ba4c073e0677', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '01bd2a64-1fe0-4f73-b4a4-708ace2d66cc', 'X-Kubernetes-Pf-Prioritylevel-Uid': '2b0e927d-eaed-425c-9078-1775d75ad11d', 'Date': 'Sun, 22 Sep 2024 12:21:33 GMT', 'Content-Length': '204'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"context-cyan\" not found","reason":"NotFound","details":{"name":"context-cyan","kind":"namespaces"},"code":404}