WARNING  kubetest:utils.py:139 got api exception while waiting: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f2b91b11-0b74-4b94-a15f-ae5224d14e3d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ebec9aac-e246-47f7-9147-da62f98e4c92', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'ef2f740c-628e-48f3-b60d-623770a97fb8', 'Date': 'Mon, 07 Oct 2024 23:21:55 GMT', 'Content-Length': '204'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"context-cyan\" not found","reason":"NotFound","details":{"name":"context-cyan","kind":"namespaces"},"code":404}