WARNING  kubetest:utils.py:139 got api exception while waiting: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f525a473-86d7-4a33-976d-f37ac3d6b184', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '553ff815-9b14-4c1e-bfb1-9039759cfc9a', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'fdb055d4-e86a-40a5-a5bb-1e38d29ac3ab', 'Date': 'Sat, 21 Sep 2024 11:13:30 GMT', 'Content-Length': '204'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"context-cyan\" not found","reason":"NotFound","details":{"name":"context-cyan","kind":"namespaces"},"code":404}